# Netlify configuration for Next.js 15+
[build]
  command = "pnpm run build"
  publish = ".next"

[functions]
  directory = ".netlify/functions"

[dev]
  command = "pnpm run dev"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Optional: Set environment variables here
#[[build.environment]]
#  NODE_VERSION = "18"
#  NEXT_PUBLIC_API_URL = "https://your-api-url.com"
